-- =============================================================================
-- LavanderiaDB - Esquema completo
-- Base de datos: PostgreSQL 16
-- Generado: 2026-03-30
-- =============================================================================

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';
SET default_table_access_method = heap;

-- =============================================================================
-- TABLAS
-- =============================================================================

CREATE TABLE public."AuditoriaGeneral" (
    "AuditoriaID" bigint NOT NULL,
    "Tabla" character varying(100) NOT NULL,
    "Operacion" character varying(10) NOT NULL,
    "RegistroID" integer NOT NULL,
    "ValoresAnteriores" text,
    "ValoresNuevos" text,
    "UsuarioID" integer NOT NULL,
    "FechaOperacion" timestamp without time zone DEFAULT now() NOT NULL,
    "DireccionIP" character varying(45)
);

ALTER TABLE public."AuditoriaGeneral" ALTER COLUMN "AuditoriaID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AuditoriaGeneral_AuditoriaID_seq"
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE public."Categorias" (
    "CategoriaID" integer NOT NULL,
    "NombreCategoria" character varying(100) NOT NULL,
    "Descripcion" character varying(255),
    "Activo" boolean DEFAULT true NOT NULL
);

ALTER TABLE public."Categorias" ALTER COLUMN "CategoriaID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Categorias_CategoriaID_seq"
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE public."Clientes" (
    "ClienteID" integer NOT NULL,
    "NumeroCliente" character varying(20) NOT NULL,
    "NombreCompleto" character varying(150) NOT NULL,
    "Telefono" character varying(20) NOT NULL,
    "Email" character varying(100),
    "Direccion" character varying(255),
    "RFC" character varying(13),
    "LimiteCredito" numeric(10,2) NOT NULL,
    "SaldoActual" numeric(10,2) NOT NULL,
    "Activo" boolean DEFAULT true NOT NULL,
    "FechaRegistro" timestamp without time zone DEFAULT now() NOT NULL,
    "RegistradoPor" integer NOT NULL
);

ALTER TABLE public."Clientes" ALTER COLUMN "ClienteID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Clientes_ClienteID_seq"
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE public."Combos" (
    "ComboID" integer NOT NULL,
    "NombreCombo" character varying(100) NOT NULL,
    "Descripcion" character varying(255),
    "PorcentajeDescuento" numeric(5,2) NOT NULL,
    "FechaInicio" date NOT NULL,
    "FechaFin" date,
    "Activo" boolean DEFAULT true NOT NULL
);

ALTER TABLE public."Combos" ALTER COLUMN "ComboID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Combos_ComboID_seq"
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE public."CombosDetalle" (
    "ComboDetalleID" integer NOT NULL,
    "ComboID" integer NOT NULL,
    "ServicioPrendaID" integer NOT NULL,
    "CantidadMinima" integer NOT NULL
);

ALTER TABLE public."CombosDetalle" ALTER COLUMN "ComboDetalleID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."CombosDetalle_ComboDetalleID_seq"
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE public."ConfiguracionReportes" (
    "ConfigReporteID" integer NOT NULL,
    "NombreReporte" character varying(100) NOT NULL,
    "TipoReporte" character varying(50) NOT NULL,
    "Frecuencia" character varying(20) NOT NULL,
    "FormatoExportacion" character varying(20) NOT NULL,
    "DestinatariosEmail" character varying(500),
    "HoraEnvio" character varying(5),
    "Activo" boolean DEFAULT true NOT NULL,
    "ParametrosJSON" text
);

ALTER TABLE public."ConfiguracionReportes" ALTER COLUMN "ConfigReporteID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."ConfiguracionReportes_ConfigReporteID_seq"
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE public."CortesCaja" (
    "CorteID" integer NOT NULL,
    "FolioCorte" character varying(30) NOT NULL,
    "CajeroID" integer NOT NULL,
    "TurnoDescripcion" character varying(50),
    "FechaInicio" timestamp without time zone NOT NULL,
    "FechaFin" timestamp without time zone NOT NULL,
    "FechaCorte" timestamp without time zone DEFAULT now() NOT NULL,
    "FondoInicial" numeric(10,2),
    "TotalEsperadoEfectivo" numeric(10,2) NOT NULL,
    "TotalEsperadoTarjeta" numeric(10,2) NOT NULL,
    "TotalEsperadoTransferencia" numeric(10,2) NOT NULL,
    "TotalEsperadoOtros" numeric(10,2) NOT NULL,
    "TotalEsperado" numeric(10,2) NOT NULL,
    "TotalDeclaradoEfectivo" numeric(10,2) NOT NULL,
    "TotalDeclaradoTarjeta" numeric(10,2) NOT NULL,
    "TotalDeclaradoTransferencia" numeric(10,2) NOT NULL,
    "TotalDeclaradoOtros" numeric(10,2) NOT NULL,
    "TotalDeclarado" numeric(10,2) NOT NULL,
    "DiferenciaInicialEfectivo" numeric(11,2),
    "DiferenciaInicialTarjeta" numeric(11,2),
    "DiferenciaInicialTransferencia" numeric(11,2),
    "DiferenciaInicialOtros" numeric(11,2),
    "DiferenciaInicial" numeric(11,2),
    "MontoAjuste" numeric(10,2) NOT NULL,
    "MotivoAjuste" character varying(500),
    "FechaAjuste" timestamp without time zone,
    "DiferenciaFinal" numeric(12,2),
    "NumeroTransacciones" integer NOT NULL,
    "Observaciones" character varying(500)
);

ALTER TABLE public."CortesCaja" ALTER COLUMN "CorteID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."CortesCaja_CorteID_seq"
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE public."CortesCajaDetalle" (
    "CorteDetalleID" integer NOT NULL,
    "CorteID" integer NOT NULL,
    "MetodoPagoID" integer NOT NULL,
    "NumeroTransacciones" integer NOT NULL,
    "TotalEsperado" numeric(10,2) NOT NULL,
    "TotalDeclarado" numeric(10,2) NOT NULL,
    "Diferencia" numeric(11,2)
);

ALTER TABLE public."CortesCajaDetalle" ALTER COLUMN "CorteDetalleID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."CortesCajaDetalle_CorteDetalleID_seq"
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE public."Descuentos" (
    "DescuentoID" integer NOT NULL,
    "NombreDescuento" character varying(100) NOT NULL,
    "TipoDescuento" character varying(20) NOT NULL,
    "Valor" numeric(10,2) NOT NULL,
    "FechaInicio" date NOT NULL,
    "FechaFin" date,
    "Activo" boolean DEFAULT true NOT NULL
);

ALTER TABLE public."Descuentos" ALTER COLUMN "DescuentoID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Descuentos_DescuentoID_seq"
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE public."EstadosOrden" (
    "EstadoOrdenID" integer NOT NULL,
    "NombreEstado" character varying(50) NOT NULL,
    "ColorEstado" character varying(7),
    "OrdenProceso" integer NOT NULL
);

ALTER TABLE public."EstadosOrden" ALTER COLUMN "EstadoOrdenID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."EstadosOrden_EstadoOrdenID_seq"
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE public."HistorialEstadosOrden" (
    "HistorialEstadoID" integer NOT NULL,
    "OrdenID" integer NOT NULL,
    "EstadoOrdenID" integer NOT NULL,
    "FechaCambio" timestamp without time zone DEFAULT now() NOT NULL,
    "CambiadoPor" integer NOT NULL,
    "Comentarios" character varying(500)
);

ALTER TABLE public."HistorialEstadosOrden" ALTER COLUMN "HistorialEstadoID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."HistorialEstadosOrden_HistorialEstadoID_seq"
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE public."HistorialReportes" (
    "HistorialReporteID" integer NOT NULL,
    "ConfigReporteID" integer NOT NULL,
    "FechaGeneracion" timestamp without time zone DEFAULT now() NOT NULL,
    "FechaEnvio" timestamp without time zone,
    "Estado" character varying(20) NOT NULL,
    "RutaArchivo" character varying(500),
    "MensajeError" text
);

ALTER TABLE public."HistorialReportes" ALTER COLUMN "HistorialReporteID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."HistorialReportes_HistorialReporteID_seq"
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE public."MetodosPago" (
    "MetodoPagoID" integer NOT NULL,
    "NombreMetodo" character varying(50) NOT NULL,
    "RequiereReferencia" boolean NOT NULL,
    "Activo" boolean DEFAULT true NOT NULL
);

ALTER TABLE public."MetodosPago" ALTER COLUMN "MetodoPagoID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."MetodosPago_MetodoPagoID_seq"
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE public."Ordenes" (
    "OrdenID" integer NOT NULL,
    "FolioOrden" character varying(30) NOT NULL,
    "ClienteID" integer NOT NULL,
    "FechaRecepcion" timestamp without time zone DEFAULT now() NOT NULL,
    "FechaPrometida" timestamp without time zone NOT NULL,
    "FechaEntrega" timestamp without time zone,
    "EstadoOrdenID" integer NOT NULL,
    "Subtotal" numeric(10,2) NOT NULL,
    "Descuento" numeric(10,2) NOT NULL,
    "Total" numeric(10,2) NOT NULL,
    "Observaciones" character varying(500),
    "Ubicaciones" character varying(500),
    "RecibidoPor" integer NOT NULL,
    "EntregadoPor" integer
);

ALTER TABLE public."Ordenes" ALTER COLUMN "OrdenID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Ordenes_OrdenID_seq"
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE public."OrdenesDescuentos" (
    "OrdenDescuentoID" integer NOT NULL,
    "OrdenID" integer NOT NULL,
    "DescuentoID" integer,
    "ComboID" integer,
    "MontoDescuento" numeric(10,2) NOT NULL,
    "Justificacion" character varying(255),
    "AplicadoPor" integer NOT NULL
);

ALTER TABLE public."OrdenesDescuentos" ALTER COLUMN "OrdenDescuentoID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."OrdenesDescuentos_OrdenDescuentoID_seq"
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE public."OrdenesDetalle" (
    "OrdenDetalleID" integer NOT NULL,
    "OrdenID" integer NOT NULL,
    "NumeroLinea" integer NOT NULL,
    "ServicioID" integer NOT NULL,
    "ServicioPrendaID" integer,
    "PesoKilos" numeric(6,2),
    "Cantidad" integer,
    "PrecioUnitario" numeric(10,2) NOT NULL,
    "Subtotal" numeric(10,2) NOT NULL,
    "DescuentoLinea" numeric(10,2) NOT NULL,
    "TotalLinea" numeric(10,2) NOT NULL,
    "Observaciones" character varying(500)
);

ALTER TABLE public."OrdenesDetalle" ALTER COLUMN "OrdenDetalleID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."OrdenesDetalle_OrdenDetalleID_seq"
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE public."Pagos" (
    "PagoID" integer NOT NULL,
    "FolioPago" character varying(30) NOT NULL,
    "OrdenID" integer NOT NULL,
    "FechaPago" timestamp without time zone DEFAULT now() NOT NULL,
    "MontoPago" numeric(10,2) NOT NULL,
    "RecibioPor" integer NOT NULL,
    "Observaciones" character varying(500),
    "CanceladoEn" timestamp without time zone,
    "CanceladoPor" integer
);

ALTER TABLE public."Pagos" ALTER COLUMN "PagoID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Pagos_PagoID_seq"
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE public."PagosDetalle" (
    "PagoDetalleID" integer NOT NULL,
    "PagoID" integer NOT NULL,
    "MetodoPagoID" integer NOT NULL,
    "MontoPagado" numeric(10,2) NOT NULL,
    "Referencia" character varying(100)
);

ALTER TABLE public."PagosDetalle" ALTER COLUMN "PagoDetalleID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."PagosDetalle_PagoDetalleID_seq"
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE public."Permisos" (
    "PermisoID" integer NOT NULL,
    "NombrePermiso" character varying(100) NOT NULL,
    "Modulo" character varying(50) NOT NULL,
    "Seccion" character varying(50) NOT NULL,
    "Etiqueta" character varying(150) NOT NULL,
    "Descripcion" character varying(255)
);

ALTER TABLE public."Permisos" ALTER COLUMN "PermisoID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Permisos_PermisoID_seq"
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE public."Roles" (
    "RolID" integer NOT NULL,
    "NombreRol" character varying(50) NOT NULL,
    "Descripcion" character varying(255),
    "Activo" boolean DEFAULT true NOT NULL
);

ALTER TABLE public."Roles" ALTER COLUMN "RolID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Roles_RolID_seq"
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE public."RolesPermisos" (
    "RolPermisoID" integer NOT NULL,
    "RolID" integer NOT NULL,
    "PermisoID" integer NOT NULL
);

ALTER TABLE public."RolesPermisos" ALTER COLUMN "RolPermisoID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."RolesPermisos_RolPermisoID_seq"
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE public."Servicios" (
    "ServicioID" integer NOT NULL,
    "CategoriaID" integer NOT NULL,
    "CodigoServicio" character varying(20) NOT NULL,
    "NombreServicio" character varying(100) NOT NULL,
    "TipoCobroServicio" character varying(20) NOT NULL,
    "PrecioPorKilo" numeric(10,2),
    "PesoMinimo" numeric(6,2),
    "PesoMaximo" numeric(6,2),
    "Descripcion" character varying(500),
    "TiempoEstimado" integer,
    "Activo" boolean DEFAULT true NOT NULL,
    "FechaCreacion" timestamp without time zone DEFAULT now() NOT NULL
);

ALTER TABLE public."Servicios" ALTER COLUMN "ServicioID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Servicios_ServicioID_seq"
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE public."ServiciosPrendas" (
    "ServicioPrendaID" integer NOT NULL,
    "ServicioID" integer NOT NULL,
    "TipoPrendaID" integer NOT NULL,
    "PrecioUnitario" numeric(10,2) NOT NULL,
    "Activo" boolean DEFAULT true NOT NULL,
    "FechaActualizacion" timestamp without time zone DEFAULT now() NOT NULL
);

ALTER TABLE public."ServiciosPrendas" ALTER COLUMN "ServicioPrendaID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."ServiciosPrendas_ServicioPrendaID_seq"
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE public."TiposPrenda" (
    "TipoPrendaID" integer NOT NULL,
    "NombrePrenda" character varying(100) NOT NULL,
    "Descripcion" character varying(255),
    "Activo" boolean DEFAULT true NOT NULL
);

ALTER TABLE public."TiposPrenda" ALTER COLUMN "TipoPrendaID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."TiposPrenda_TipoPrendaID_seq"
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE public."Usuarios" (
    "UsuarioID" integer NOT NULL,
    "NombreUsuario" character varying(50) NOT NULL,
    "Email" character varying(100) NOT NULL,
    "PasswordHash" character varying(255) NOT NULL,
    "NombreCompleto" character varying(150) NOT NULL,
    "Activo" boolean DEFAULT true NOT NULL,
    "FechaCreacion" timestamp without time zone DEFAULT now() NOT NULL,
    "UltimoAcceso" timestamp without time zone,
    "CreadoPor" integer
);

ALTER TABLE public."Usuarios" ALTER COLUMN "UsuarioID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Usuarios_UsuarioID_seq"
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE public."UsuariosRoles" (
    "UsuarioRolID" integer NOT NULL,
    "UsuarioID" integer NOT NULL,
    "RolID" integer NOT NULL,
    "FechaAsignacion" timestamp without time zone DEFAULT now() NOT NULL
);

ALTER TABLE public."UsuariosRoles" ALTER COLUMN "UsuarioRolID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."UsuariosRoles_UsuarioRolID_seq"
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);

-- =============================================================================
-- PRIMARY KEYS
-- =============================================================================

ALTER TABLE ONLY public."AuditoriaGeneral"       ADD CONSTRAINT "PK_AuditoriaGeneral"       PRIMARY KEY ("AuditoriaID");
ALTER TABLE ONLY public."Categorias"             ADD CONSTRAINT "PK_Categorias"             PRIMARY KEY ("CategoriaID");
ALTER TABLE ONLY public."Clientes"               ADD CONSTRAINT "PK_Clientes"               PRIMARY KEY ("ClienteID");
ALTER TABLE ONLY public."Combos"                 ADD CONSTRAINT "PK_Combos"                 PRIMARY KEY ("ComboID");
ALTER TABLE ONLY public."CombosDetalle"          ADD CONSTRAINT "PK_CombosDetalle"          PRIMARY KEY ("ComboDetalleID");
ALTER TABLE ONLY public."ConfiguracionReportes"  ADD CONSTRAINT "PK_ConfiguracionReportes"  PRIMARY KEY ("ConfigReporteID");
ALTER TABLE ONLY public."CortesCaja"             ADD CONSTRAINT "PK_CortesCaja"             PRIMARY KEY ("CorteID");
ALTER TABLE ONLY public."CortesCajaDetalle"      ADD CONSTRAINT "PK_CortesCajaDetalle"      PRIMARY KEY ("CorteDetalleID");
ALTER TABLE ONLY public."Descuentos"             ADD CONSTRAINT "PK_Descuentos"             PRIMARY KEY ("DescuentoID");
ALTER TABLE ONLY public."EstadosOrden"           ADD CONSTRAINT "PK_EstadosOrden"           PRIMARY KEY ("EstadoOrdenID");
ALTER TABLE ONLY public."HistorialEstadosOrden"  ADD CONSTRAINT "PK_HistorialEstadosOrden"  PRIMARY KEY ("HistorialEstadoID");
ALTER TABLE ONLY public."HistorialReportes"      ADD CONSTRAINT "PK_HistorialReportes"      PRIMARY KEY ("HistorialReporteID");
ALTER TABLE ONLY public."MetodosPago"            ADD CONSTRAINT "PK_MetodosPago"            PRIMARY KEY ("MetodoPagoID");
ALTER TABLE ONLY public."Ordenes"                ADD CONSTRAINT "PK_Ordenes"                PRIMARY KEY ("OrdenID");
ALTER TABLE ONLY public."OrdenesDescuentos"      ADD CONSTRAINT "PK_OrdenesDescuentos"      PRIMARY KEY ("OrdenDescuentoID");
ALTER TABLE ONLY public."OrdenesDetalle"         ADD CONSTRAINT "PK_OrdenesDetalle"         PRIMARY KEY ("OrdenDetalleID");
ALTER TABLE ONLY public."Pagos"                  ADD CONSTRAINT "PK_Pagos"                  PRIMARY KEY ("PagoID");
ALTER TABLE ONLY public."PagosDetalle"           ADD CONSTRAINT "PK_PagosDetalle"           PRIMARY KEY ("PagoDetalleID");
ALTER TABLE ONLY public."Permisos"               ADD CONSTRAINT "PK_Permisos"               PRIMARY KEY ("PermisoID");
ALTER TABLE ONLY public."Roles"                  ADD CONSTRAINT "PK_Roles"                  PRIMARY KEY ("RolID");
ALTER TABLE ONLY public."RolesPermisos"          ADD CONSTRAINT "PK_RolesPermisos"          PRIMARY KEY ("RolPermisoID");
ALTER TABLE ONLY public."Servicios"              ADD CONSTRAINT "PK_Servicios"              PRIMARY KEY ("ServicioID");
ALTER TABLE ONLY public."ServiciosPrendas"       ADD CONSTRAINT "PK_ServiciosPrendas"       PRIMARY KEY ("ServicioPrendaID");
ALTER TABLE ONLY public."TiposPrenda"            ADD CONSTRAINT "PK_TiposPrenda"            PRIMARY KEY ("TipoPrendaID");
ALTER TABLE ONLY public."Usuarios"               ADD CONSTRAINT "PK_Usuarios"               PRIMARY KEY ("UsuarioID");
ALTER TABLE ONLY public."UsuariosRoles"          ADD CONSTRAINT "PK_UsuariosRoles"          PRIMARY KEY ("UsuarioRolID");
ALTER TABLE ONLY public."__EFMigrationsHistory"  ADD CONSTRAINT "PK___EFMigrationsHistory"  PRIMARY KEY ("MigrationId");

-- =============================================================================
-- ÍNDICES
-- =============================================================================

CREATE INDEX "IX_AuditoriaGeneral_Tabla_FechaOperacion" ON public."AuditoriaGeneral" USING btree ("Tabla", "FechaOperacion" DESC);
CREATE INDEX "IX_AuditoriaGeneral_UsuarioID"            ON public."AuditoriaGeneral" USING btree ("UsuarioID");
CREATE INDEX "IX_Clientes_RegistradoPor"                ON public."Clientes"         USING btree ("RegistradoPor");
CREATE INDEX "IX_CombosDetalle_ComboID"                 ON public."CombosDetalle"    USING btree ("ComboID");
CREATE INDEX "IX_CombosDetalle_ServicioPrendaID"        ON public."CombosDetalle"    USING btree ("ServicioPrendaID");
CREATE INDEX "IX_CortesCajaDetalle_CorteID"             ON public."CortesCajaDetalle" USING btree ("CorteID");
CREATE INDEX "IX_CortesCajaDetalle_MetodoPagoID"        ON public."CortesCajaDetalle" USING btree ("MetodoPagoID");
CREATE INDEX "IX_CortesCaja_Cajero"                     ON public."CortesCaja"       USING btree ("CajeroID");
CREATE INDEX "IX_CortesCaja_FechaCorte"                 ON public."CortesCaja"       USING btree ("FechaCorte");
CREATE INDEX "IX_CortesCaja_FechaInicio"                ON public."CortesCaja"       USING btree ("FechaInicio", "FechaFin");
CREATE INDEX "IX_HistorialEstadosOrden_CambiadoPor"     ON public."HistorialEstadosOrden" USING btree ("CambiadoPor");
CREATE INDEX "IX_HistorialEstadosOrden_EstadoOrdenID"   ON public."HistorialEstadosOrden" USING btree ("EstadoOrdenID");
CREATE INDEX "IX_HistorialEstadosOrden_OrdenID"         ON public."HistorialEstadosOrden" USING btree ("OrdenID");
CREATE INDEX "IX_HistorialReportes_ConfigReporteID"     ON public."HistorialReportes" USING btree ("ConfigReporteID");
CREATE INDEX "IX_OrdenesDescuentos_AplicadoPor"         ON public."OrdenesDescuentos" USING btree ("AplicadoPor");
CREATE INDEX "IX_OrdenesDescuentos_ComboID"             ON public."OrdenesDescuentos" USING btree ("ComboID");
CREATE INDEX "IX_OrdenesDescuentos_DescuentoID"         ON public."OrdenesDescuentos" USING btree ("DescuentoID");
CREATE INDEX "IX_OrdenesDescuentos_OrdenID"             ON public."OrdenesDescuentos" USING btree ("OrdenID");
CREATE INDEX "IX_OrdenesDetalle_OrdenID"                ON public."OrdenesDetalle"   USING btree ("OrdenID");
CREATE INDEX "IX_OrdenesDetalle_ServicioID"             ON public."OrdenesDetalle"   USING btree ("ServicioID");
CREATE INDEX "IX_OrdenesDetalle_ServicioPrendaID"       ON public."OrdenesDetalle"   USING btree ("ServicioPrendaID");
CREATE INDEX "IX_Ordenes_ClienteID"                     ON public."Ordenes"           USING btree ("ClienteID");
CREATE INDEX "IX_Ordenes_EntregadoPor"                  ON public."Ordenes"           USING btree ("EntregadoPor");
CREATE INDEX "IX_Ordenes_EstadoOrdenID"                 ON public."Ordenes"           USING btree ("EstadoOrdenID");
CREATE INDEX "IX_Ordenes_FechaRecepcion"                ON public."Ordenes"           USING btree ("FechaRecepcion" DESC);
CREATE INDEX "IX_Ordenes_RecibidoPor"                   ON public."Ordenes"           USING btree ("RecibidoPor");
CREATE INDEX "IX_PagosDetalle_MetodoPagoID"             ON public."PagosDetalle"      USING btree ("MetodoPagoID");
CREATE INDEX "IX_PagosDetalle_PagoID"                   ON public."PagosDetalle"      USING btree ("PagoID");
CREATE INDEX "IX_Pagos_OrdenID"                         ON public."Pagos"             USING btree ("OrdenID");
CREATE INDEX "IX_Pagos_RecibioPor"                      ON public."Pagos"             USING btree ("RecibioPor");
CREATE INDEX "IX_Permisos_Modulo"                       ON public."Permisos"          USING btree ("Modulo");
CREATE INDEX "IX_RolesPermisos_PermisoID"               ON public."RolesPermisos"     USING btree ("PermisoID");
CREATE INDEX "IX_RolesPermisos_RolID"                   ON public."RolesPermisos"     USING btree ("RolID");
CREATE INDEX "IX_Roles_Activo"                          ON public."Roles"             USING btree ("Activo");
CREATE INDEX "IX_ServiciosPrendas_ServicioID"           ON public."ServiciosPrendas"  USING btree ("ServicioID");
CREATE INDEX "IX_ServiciosPrendas_TipoPrendaID"         ON public."ServiciosPrendas"  USING btree ("TipoPrendaID");
CREATE INDEX "IX_Servicios_Activo"                      ON public."Servicios"         USING btree ("Activo");
CREATE INDEX "IX_Servicios_CategoriaID"                 ON public."Servicios"         USING btree ("CategoriaID");
CREATE INDEX "IX_Servicios_TipoCobroServicio"           ON public."Servicios"         USING btree ("TipoCobroServicio");
CREATE INDEX "IX_UsuariosRoles_RolID"                   ON public."UsuariosRoles"     USING btree ("RolID");
CREATE INDEX "IX_UsuariosRoles_UsuarioID"               ON public."UsuariosRoles"     USING btree ("UsuarioID");
CREATE INDEX "IX_Usuarios_Activo"                       ON public."Usuarios"          USING btree ("Activo");
CREATE INDEX "IX_Usuarios_CreadoPor"                    ON public."Usuarios"          USING btree ("CreadoPor") WHERE ("CreadoPor" IS NOT NULL);

-- =============================================================================
-- ÍNDICES ÚNICOS
-- =============================================================================

CREATE UNIQUE INDEX "UK_Categorias_NombreCategoria"      ON public."Categorias"       USING btree ("NombreCategoria");
CREATE UNIQUE INDEX "UK_Clientes_NumeroCliente"          ON public."Clientes"         USING btree ("NumeroCliente");
CREATE UNIQUE INDEX "UK_CortesCaja_Folio"                ON public."CortesCaja"       USING btree ("FolioCorte");
CREATE UNIQUE INDEX "UK_EstadosOrden_NombreEstado"       ON public."EstadosOrden"     USING btree ("NombreEstado");
CREATE UNIQUE INDEX "UK_MetodosPago_NombreMetodo"        ON public."MetodosPago"      USING btree ("NombreMetodo");
CREATE UNIQUE INDEX "UK_Ordenes_FolioOrden"              ON public."Ordenes"           USING btree ("FolioOrden");
CREATE UNIQUE INDEX "UK_Pagos_FolioPago"                 ON public."Pagos"             USING btree ("FolioPago");
CREATE UNIQUE INDEX "UK_Permisos_NombrePermiso"          ON public."Permisos"          USING btree ("NombrePermiso");
CREATE UNIQUE INDEX "UK_RolesPermisos_Rol_Permiso"       ON public."RolesPermisos"     USING btree ("RolID", "PermisoID");
CREATE UNIQUE INDEX "UK_Roles_NombreRol"                 ON public."Roles"             USING btree ("NombreRol");
CREATE UNIQUE INDEX "UK_ServiciosPrendas_Servicio_Prenda" ON public."ServiciosPrendas" USING btree ("ServicioID", "TipoPrendaID");
CREATE UNIQUE INDEX "UK_Servicios_CodigoServicio"        ON public."Servicios"         USING btree ("CodigoServicio");
CREATE UNIQUE INDEX "UK_TiposPrenda_NombrePrenda"        ON public."TiposPrenda"       USING btree ("NombrePrenda");
CREATE UNIQUE INDEX "UK_UsuariosRoles_Usuario_Rol"       ON public."UsuariosRoles"     USING btree ("UsuarioID", "RolID");
CREATE UNIQUE INDEX "UK_Usuarios_Email"                  ON public."Usuarios"          USING btree ("Email");
CREATE UNIQUE INDEX "UK_Usuarios_NombreUsuario"          ON public."Usuarios"          USING btree ("NombreUsuario");

-- =============================================================================
-- FOREIGN KEYS
-- =============================================================================

ALTER TABLE ONLY public."AuditoriaGeneral"
    ADD CONSTRAINT "FK_AuditoriaGeneral_UsuarioID"          FOREIGN KEY ("UsuarioID")       REFERENCES public."Usuarios"("UsuarioID");

ALTER TABLE ONLY public."Clientes"
    ADD CONSTRAINT "FK_Clientes_RegistradoPor"              FOREIGN KEY ("RegistradoPor")   REFERENCES public."Usuarios"("UsuarioID");

ALTER TABLE ONLY public."CombosDetalle"
    ADD CONSTRAINT "FK_CombosDetalle_ComboID"               FOREIGN KEY ("ComboID")         REFERENCES public."Combos"("ComboID");
ALTER TABLE ONLY public."CombosDetalle"
    ADD CONSTRAINT "FK_CombosDetalle_ServicioPrendaID"      FOREIGN KEY ("ServicioPrendaID") REFERENCES public."ServiciosPrendas"("ServicioPrendaID");

ALTER TABLE ONLY public."CortesCajaDetalle"
    ADD CONSTRAINT "FK_CortesCajaDetalle_Corte"             FOREIGN KEY ("CorteID")         REFERENCES public."CortesCaja"("CorteID") ON DELETE CASCADE;
ALTER TABLE ONLY public."CortesCajaDetalle"
    ADD CONSTRAINT "FK_CortesCajaDetalle_Metodo"            FOREIGN KEY ("MetodoPagoID")    REFERENCES public."MetodosPago"("MetodoPagoID");

ALTER TABLE ONLY public."CortesCaja"
    ADD CONSTRAINT "FK_CortesCaja_Cajero"                   FOREIGN KEY ("CajeroID")        REFERENCES public."Usuarios"("UsuarioID");

ALTER TABLE ONLY public."HistorialEstadosOrden"
    ADD CONSTRAINT "FK_HistorialEstadosOrden_CambiadoPor"   FOREIGN KEY ("CambiadoPor")     REFERENCES public."Usuarios"("UsuarioID");
ALTER TABLE ONLY public."HistorialEstadosOrden"
    ADD CONSTRAINT "FK_HistorialEstadosOrden_EstadoOrdenID" FOREIGN KEY ("EstadoOrdenID")   REFERENCES public."EstadosOrden"("EstadoOrdenID");
ALTER TABLE ONLY public."HistorialEstadosOrden"
    ADD CONSTRAINT "FK_HistorialEstadosOrden_OrdenID"       FOREIGN KEY ("OrdenID")         REFERENCES public."Ordenes"("OrdenID");

ALTER TABLE ONLY public."HistorialReportes"
    ADD CONSTRAINT "FK_HistorialReportes_ConfigReporteID"   FOREIGN KEY ("ConfigReporteID") REFERENCES public."ConfiguracionReportes"("ConfigReporteID");

ALTER TABLE ONLY public."OrdenesDescuentos"
    ADD CONSTRAINT "FK_OrdenesDescuentos_AplicadoPor"       FOREIGN KEY ("AplicadoPor")     REFERENCES public."Usuarios"("UsuarioID");
ALTER TABLE ONLY public."OrdenesDescuentos"
    ADD CONSTRAINT "FK_OrdenesDescuentos_ComboID"           FOREIGN KEY ("ComboID")         REFERENCES public."Combos"("ComboID");
ALTER TABLE ONLY public."OrdenesDescuentos"
    ADD CONSTRAINT "FK_OrdenesDescuentos_DescuentoID"       FOREIGN KEY ("DescuentoID")     REFERENCES public."Descuentos"("DescuentoID");
ALTER TABLE ONLY public."OrdenesDescuentos"
    ADD CONSTRAINT "FK_OrdenesDescuentos_OrdenID"           FOREIGN KEY ("OrdenID")         REFERENCES public."Ordenes"("OrdenID");

ALTER TABLE ONLY public."OrdenesDetalle"
    ADD CONSTRAINT "FK_OrdenesDetalle_OrdenID"              FOREIGN KEY ("OrdenID")         REFERENCES public."Ordenes"("OrdenID");
ALTER TABLE ONLY public."OrdenesDetalle"
    ADD CONSTRAINT "FK_OrdenesDetalle_ServicioID"           FOREIGN KEY ("ServicioID")      REFERENCES public."Servicios"("ServicioID");
ALTER TABLE ONLY public."OrdenesDetalle"
    ADD CONSTRAINT "FK_OrdenesDetalle_ServicioPrendaID"     FOREIGN KEY ("ServicioPrendaID") REFERENCES public."ServiciosPrendas"("ServicioPrendaID");

ALTER TABLE ONLY public."Ordenes"
    ADD CONSTRAINT "FK_Ordenes_ClienteID"                   FOREIGN KEY ("ClienteID")       REFERENCES public."Clientes"("ClienteID");
ALTER TABLE ONLY public."Ordenes"
    ADD CONSTRAINT "FK_Ordenes_EntregadoPor"                FOREIGN KEY ("EntregadoPor")    REFERENCES public."Usuarios"("UsuarioID");
ALTER TABLE ONLY public."Ordenes"
    ADD CONSTRAINT "FK_Ordenes_EstadoOrdenID"               FOREIGN KEY ("EstadoOrdenID")   REFERENCES public."EstadosOrden"("EstadoOrdenID");
ALTER TABLE ONLY public."Ordenes"
    ADD CONSTRAINT "FK_Ordenes_RecibidoPor"                 FOREIGN KEY ("RecibidoPor")     REFERENCES public."Usuarios"("UsuarioID");

ALTER TABLE ONLY public."PagosDetalle"
    ADD CONSTRAINT "FK_PagosDetalle_MetodoPagoID"           FOREIGN KEY ("MetodoPagoID")    REFERENCES public."MetodosPago"("MetodoPagoID");
ALTER TABLE ONLY public."PagosDetalle"
    ADD CONSTRAINT "FK_PagosDetalle_PagoID"                 FOREIGN KEY ("PagoID")          REFERENCES public."Pagos"("PagoID");

ALTER TABLE ONLY public."Pagos"
    ADD CONSTRAINT "FK_Pagos_OrdenID"                       FOREIGN KEY ("OrdenID")         REFERENCES public."Ordenes"("OrdenID");
ALTER TABLE ONLY public."Pagos"
    ADD CONSTRAINT "FK_Pagos_RecibioPor"                    FOREIGN KEY ("RecibioPor")      REFERENCES public."Usuarios"("UsuarioID");

ALTER TABLE ONLY public."RolesPermisos"
    ADD CONSTRAINT "FK_RolesPermisos_PermisoID"             FOREIGN KEY ("PermisoID")       REFERENCES public."Permisos"("PermisoID");
ALTER TABLE ONLY public."RolesPermisos"
    ADD CONSTRAINT "FK_RolesPermisos_RolID"                 FOREIGN KEY ("RolID")           REFERENCES public."Roles"("RolID");

ALTER TABLE ONLY public."ServiciosPrendas"
    ADD CONSTRAINT "FK_ServiciosPrendas_ServicioID"         FOREIGN KEY ("ServicioID")      REFERENCES public."Servicios"("ServicioID");
ALTER TABLE ONLY public."ServiciosPrendas"
    ADD CONSTRAINT "FK_ServiciosPrendas_TipoPrendaID"       FOREIGN KEY ("TipoPrendaID")    REFERENCES public."TiposPrenda"("TipoPrendaID");

ALTER TABLE ONLY public."Servicios"
    ADD CONSTRAINT "FK_Servicios_CategoriaID"               FOREIGN KEY ("CategoriaID")     REFERENCES public."Categorias"("CategoriaID");

ALTER TABLE ONLY public."UsuariosRoles"
    ADD CONSTRAINT "FK_UsuariosRoles_RolID"                 FOREIGN KEY ("RolID")           REFERENCES public."Roles"("RolID");
ALTER TABLE ONLY public."UsuariosRoles"
    ADD CONSTRAINT "FK_UsuariosRoles_UsuarioID"             FOREIGN KEY ("UsuarioID")       REFERENCES public."Usuarios"("UsuarioID");

ALTER TABLE ONLY public."Usuarios"
    ADD CONSTRAINT "FK_Usuarios_CreadoPor"                  FOREIGN KEY ("CreadoPor")       REFERENCES public."Usuarios"("UsuarioID");

-- =============================================================================
-- EF CORE MIGRATIONS HISTORY
-- =============================================================================

INSERT INTO public."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260330064133_InitialPostgres', '8.0.11')
ON CONFLICT ("MigrationId") DO NOTHING;
