// <auto-generated />
using System;
using LaundryManagement.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LaundryManagement.Infrastructure.Migrations
{
    [DbContext(typeof(LaundryDbContext))]
    [Migration("20251229211925_EliminaUbicacionesAgregaCampoTexto")]
    partial class EliminaUbicacionesAgregaCampoTexto
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LaundryManagement.Infrastructure.AuditoriaGeneral", b =>
                {
                    b.Property<long>("AuditoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("AuditoriaID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AuditoriaId"));

                    b.Property<string>("DireccionIp")
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("DireccionIP");

                    b.Property<DateTime>("FechaOperacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Operacion")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<int>("RegistroId")
                        .HasColumnType("int")
                        .HasColumnName("RegistroID");

                    b.Property<string>("Tabla")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("UsuarioID");

                    b.Property<string>("ValoresAnteriores")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("ValoresNuevos")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.HasKey("AuditoriaId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex(new[] { "Tabla", "FechaOperacion" }, "IX_AuditoriaGeneral_Tabla_FechaOperacion")
                        .IsDescending(false, true);

                    b.ToTable("AuditoriaGeneral", (string)null);
                });

            modelBuilder.Entity("LaundryManagement.Infrastructure.Categoria", b =>
                {
                    b.Property<int>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CategoriaID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoriaId"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("NombreCategoria")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("CategoriaId");

                    b.HasIndex(new[] { "NombreCategoria" }, "UK_Categorias_NombreCategoria")
                        .IsUnique();

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("LaundryManagement.Infrastructure.Cliente", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ClienteID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClienteId"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Direccion")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal>("LimiteCredito")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("NumeroCliente")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("RegistradoPor")
                        .HasColumnType("int");

                    b.Property<string>("Rfc")
                        .HasMaxLength(13)
                        .IsUnicode(false)
                        .HasColumnType("varchar(13)")
                        .HasColumnName("RFC");

                    b.Property<decimal>("SaldoActual")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("ClienteId");

                    b.HasIndex("RegistradoPor");

                    b.HasIndex(new[] { "NumeroCliente" }, "UK_Clientes_NumeroCliente")
                        .IsUnique();

                    b.ToTable("Clientes", t =>
                        {
                            t.HasTrigger("TRG_Clientes_GenerarNumeroCliente");

                            t.HasTrigger("TRG_Clientes_ValidarLimiteCredito");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("LaundryManagement.Infrastructure.Combo", b =>
                {
                    b.Property<int>("ComboId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ComboID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ComboId"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateOnly?>("FechaFin")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<string>("NombreCombo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("PorcentajeDescuento")
                        .HasColumnType("decimal(5, 2)");

                    b.HasKey("ComboId");

                    b.ToTable("Combos");
                });

            modelBuilder.Entity("LaundryManagement.Infrastructure.CombosDetalle", b =>
                {
                    b.Property<int>("ComboDetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ComboDetalleID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ComboDetalleId"));

                    b.Property<int>("CantidadMinima")
                        .HasColumnType("int");

                    b.Property<int>("ComboId")
                        .HasColumnType("int")
                        .HasColumnName("ComboID");

                    b.Property<int>("ServicioPrendaId")
                        .HasColumnType("int")
                        .HasColumnName("ServicioPrendaID");

                    b.HasKey("ComboDetalleId");

                    b.HasIndex("ComboId");

                    b.HasIndex("ServicioPrendaId");

                    b.ToTable("CombosDetalle", (string)null);
                });

            modelBuilder.Entity("LaundryManagement.Infrastructure.ConfiguracionReporte", b =>
                {
                    b.Property<int>("ConfigReporteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ConfigReporteID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConfigReporteId"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("DestinatariosEmail")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("FormatoExportacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Frecuencia")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("HoraEnvio")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)");

                    b.Property<string>("NombreReporte")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ParametrosJson")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("ParametrosJSON");

                    b.Property<string>("TipoReporte")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("ConfigReporteId");

                    b.ToTable("ConfiguracionReportes");
                });

            modelBuilder.Entity("LaundryManagement.Infrastructure.CortesCaja", b =>
                {
                    b.Property<int>("CorteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CorteID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CorteId"));

                    b.Property<int>("CajeroId")
                        .HasColumnType("int")
                        .HasColumnName("CajeroID");

                    b.Property<decimal?>("DiferenciaFinal")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(12, 2)")
                        .HasComputedColumnSql("(([TotalDeclarado]-[TotalEsperado])+[MontoAjuste])", true);

                    b.Property<decimal?>("DiferenciaInicial")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(11, 2)")
                        .HasComputedColumnSql("([TotalDeclarado]-[TotalEsperado])", true);

                    b.Property<decimal?>("DiferenciaInicialEfectivo")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(11, 2)")
                        .HasComputedColumnSql("([TotalDeclaradoEfectivo]-[TotalEsperadoEfectivo])", true);

                    b.Property<decimal?>("DiferenciaInicialOtros")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(11, 2)")
                        .HasComputedColumnSql("([TotalDeclaradoOtros]-[TotalEsperadoOtros])", true);

                    b.Property<decimal?>("DiferenciaInicialTarjeta")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(11, 2)")
                        .HasComputedColumnSql("([TotalDeclaradoTarjeta]-[TotalEsperadoTarjeta])", true);

                    b.Property<decimal?>("DiferenciaInicialTransferencia")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(11, 2)")
                        .HasComputedColumnSql("([TotalDeclaradoTransferencia]-[TotalEsperadoTransferencia])", true);

                    b.Property<DateTime?>("FechaAjuste")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("FechaCorte")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime");

                    b.Property<string>("FolioCorte")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<decimal>("MontoAjuste")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("MotivoAjuste")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("NumeroTransacciones")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<decimal>("TotalDeclarado")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("TotalDeclaradoEfectivo")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("TotalDeclaradoOtros")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("TotalDeclaradoTarjeta")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("TotalDeclaradoTransferencia")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("TotalEsperado")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("TotalEsperadoEfectivo")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("TotalEsperadoOtros")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("TotalEsperadoTarjeta")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("TotalEsperadoTransferencia")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("TurnoDescripcion")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("CorteId");

                    b.HasIndex(new[] { "CajeroId" }, "IX_CortesCaja_Cajero");

                    b.HasIndex(new[] { "FechaCorte" }, "IX_CortesCaja_FechaCorte");

                    b.HasIndex(new[] { "FechaInicio", "FechaFin" }, "IX_CortesCaja_FechaInicio");

                    b.HasIndex(new[] { "FolioCorte" }, "UK_CortesCaja_Folio")
                        .IsUnique();

                    b.ToTable("CortesCaja", (string)null);
                });

            modelBuilder.Entity("LaundryManagement.Infrastructure.CortesCajaDetalle", b =>
                {
                    b.Property<int>("CorteDetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CorteDetalleID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CorteDetalleId"));

                    b.Property<int>("CorteId")
                        .HasColumnType("int")
                        .HasColumnName("CorteID");

                    b.Property<decimal?>("Diferencia")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(11, 2)")
                        .HasComputedColumnSql("([TotalDeclarado]-[TotalEsperado])", true);

                    b.Property<int>("MetodoPagoId")
                        .HasColumnType("int")
                        .HasColumnName("MetodoPagoID");

                    b.Property<int>("NumeroTransacciones")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalDeclarado")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("TotalEsperado")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("CorteDetalleId");

                    b.HasIndex("CorteId");

                    b.HasIndex("MetodoPagoId");

                    b.ToTable("CortesCajaDetalle", (string)null);
                });

            modelBuilder.Entity("LaundryManagement.Infrastructure.Descuento", b =>
                {
                    b.Property<int>("DescuentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DescuentoID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DescuentoId"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateOnly?>("FechaFin")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<string>("NombreDescuento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("TipoDescuento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("DescuentoId");

                    b.ToTable("Descuentos");
                });

            modelBuilder.Entity("LaundryManagement.Infrastructure.EstadosOrden", b =>
                {
                    b.Property<int>("EstadoOrdenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("EstadoOrdenID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EstadoOrdenId"));

                    b.Property<string>("ColorEstado")
                        .HasMaxLength(7)
                        .IsUnicode(false)
                        .HasColumnType("varchar(7)");

                    b.Property<string>("NombreEstado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("OrdenProceso")
                        .HasColumnType("int");

                    b.HasKey("EstadoOrdenId");

                    b.HasIndex(new[] { "NombreEstado" }, "UK_EstadosOrden_NombreEstado")
                        .IsUnique();

                    b.ToTable("EstadosOrden", (string)null);
                });

            modelBuilder.Entity("LaundryManagement.Infrastructure.HistorialEstadosOrden", b =>
                {
                    b.Property<int>("HistorialEstadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("HistorialEstadoID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HistorialEstadoId"));

                    b.Property<int>("CambiadoPor")
                        .HasColumnType("int");

                    b.Property<string>("Comentarios")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("EstadoOrdenId")
                        .HasColumnType("int")
                        .HasColumnName("EstadoOrdenID");

                    b.Property<DateTime>("FechaCambio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("OrdenId")
                        .HasColumnType("int")
                        .HasColumnName("OrdenID");

                    b.HasKey("HistorialEstadoId");

                    b.HasIndex("CambiadoPor");

                    b.HasIndex("EstadoOrdenId");

                    b.HasIndex("OrdenId");

                    b.ToTable("HistorialEstadosOrden", (string)null);
                });

            modelBuilder.Entity("LaundryManagement.Infrastructure.HistorialReporte", b =>
                {
                    b.Property<int>("HistorialReporteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("HistorialReporteID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HistorialReporteId"));

                    b.Property<int>("ConfigReporteId")
                        .HasColumnType("int")
                        .HasColumnName("ConfigReporteID");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("FechaEnvio")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("FechaGeneracion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("MensajeError")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("RutaArchivo")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.HasKey("HistorialReporteId");

                    b.HasIndex("ConfigReporteId");

                    b.ToTable("HistorialReportes");
                });

            modelBuilder.Entity("LaundryManagement.Infrastructure.MetodosPago", b =>
                {
                    b.Property<int>("MetodoPagoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MetodoPagoID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MetodoPagoId"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("NombreMetodo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("RequiereReferencia")
                        .HasColumnType("bit");

                    b.HasKey("MetodoPagoId");

                    b.HasIndex(new[] { "NombreMetodo" }, "UK_MetodosPago_NombreMetodo")
                        .IsUnique();

                    b.ToTable("MetodosPago", (string)null);
                });

            modelBuilder.Entity("LaundryManagement.Infrastructure.Ordene", b =>
                {
                    b.Property<int>("OrdenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("OrdenID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrdenId"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int")
                        .HasColumnName("ClienteID");

                    b.Property<decimal>("Descuento")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("EntregadoPor")
                        .HasColumnType("int");

                    b.Property<int>("EstadoOrdenId")
                        .HasColumnType("int")
                        .HasColumnName("EstadoOrdenID");

                    b.Property<DateTime?>("FechaEntrega")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("FechaPrometida")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("FechaRecepcion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("FolioOrden")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("RecibidoPor")
                        .HasColumnType("int");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Ubicaciones")
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("OrdenId");

                    b.HasIndex("EntregadoPor");

                    b.HasIndex("RecibidoPor");

                    b.HasIndex(new[] { "ClienteId" }, "IX_Ordenes_ClienteID");

                    b.HasIndex(new[] { "EstadoOrdenId" }, "IX_Ordenes_EstadoOrdenID");

                    b.HasIndex(new[] { "FechaRecepcion" }, "IX_Ordenes_FechaRecepcion")
                        .IsDescending();

                    b.HasIndex(new[] { "FolioOrden" }, "UK_Ordenes_FolioOrden")
                        .IsUnique();

                    b.ToTable("Ordenes");
                });

            modelBuilder.Entity("LaundryManagement.Infrastructure.OrdenesDescuento", b =>
                {
                    b.Property<int>("OrdenDescuentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("OrdenDescuentoID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrdenDescuentoId"));

                    b.Property<int>("AplicadoPor")
                        .HasColumnType("int");

                    b.Property<int?>("ComboId")
                        .HasColumnType("int")
                        .HasColumnName("ComboID");

                    b.Property<int?>("DescuentoId")
                        .HasColumnType("int")
                        .HasColumnName("DescuentoID");

                    b.Property<string>("Justificacion")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("MontoDescuento")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("OrdenId")
                        .HasColumnType("int")
                        .HasColumnName("OrdenID");

                    b.HasKey("OrdenDescuentoId");

                    b.HasIndex("AplicadoPor");

                    b.HasIndex("ComboId");

                    b.HasIndex("DescuentoId");

                    b.HasIndex("OrdenId");

                    b.ToTable("OrdenesDescuentos");
                });

            modelBuilder.Entity("LaundryManagement.Infrastructure.OrdenesDetalle", b =>
                {
                    b.Property<int>("OrdenDetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("OrdenDetalleID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrdenDetalleId"));

                    b.Property<int?>("Cantidad")
                        .HasColumnType("int");

                    b.Property<decimal>("DescuentoLinea")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("NumeroLinea")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("OrdenId")
                        .HasColumnType("int")
                        .HasColumnName("OrdenID");

                    b.Property<decimal?>("PesoKilos")
                        .HasColumnType("decimal(6, 2)");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("ServicioId")
                        .HasColumnType("int")
                        .HasColumnName("ServicioID");

                    b.Property<int?>("ServicioPrendaId")
                        .HasColumnType("int")
                        .HasColumnName("ServicioPrendaID");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("TotalLinea")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("OrdenDetalleId");

                    b.HasIndex("ServicioPrendaId");

                    b.HasIndex(new[] { "OrdenId" }, "IX_OrdenesDetalle_OrdenID");

                    b.HasIndex(new[] { "ServicioId" }, "IX_OrdenesDetalle_ServicioID");

                    b.ToTable("OrdenesDetalle", (string)null);
                });

            modelBuilder.Entity("LaundryManagement.Infrastructure.Pago", b =>
                {
                    b.Property<int>("PagoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PagoID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PagoId"));

                    b.Property<DateTime>("FechaPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("FolioPago")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<decimal>("MontoPago")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("OrdenId")
                        .HasColumnType("int")
                        .HasColumnName("OrdenID");

                    b.Property<int>("RecibioPor")
                        .HasColumnType("int");

                    b.HasKey("PagoId");

                    b.HasIndex("RecibioPor");

                    b.HasIndex(new[] { "OrdenId" }, "IX_Pagos_OrdenID");

                    b.HasIndex(new[] { "FolioPago" }, "UK_Pagos_FolioPago")
                        .IsUnique();

                    b.ToTable("Pagos");
                });

            modelBuilder.Entity("LaundryManagement.Infrastructure.PagosDetalle", b =>
                {
                    b.Property<int>("PagoDetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PagoDetalleID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PagoDetalleId"));

                    b.Property<int>("MetodoPagoId")
                        .HasColumnType("int")
                        .HasColumnName("MetodoPagoID");

                    b.Property<decimal>("MontoPagado")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("PagoId")
                        .HasColumnType("int")
                        .HasColumnName("PagoID");

                    b.Property<string>("Referencia")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("PagoDetalleId");

                    b.HasIndex("MetodoPagoId");

                    b.HasIndex("PagoId");

                    b.ToTable("PagosDetalle", (string)null);
                });

            modelBuilder.Entity("LaundryManagement.Infrastructure.Permiso", b =>
                {
                    b.Property<int>("PermisoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PermisoID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PermisoId"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Modulo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NombrePermiso")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("PermisoId");

                    b.HasIndex(new[] { "Modulo" }, "IX_Permisos_Modulo");

                    b.HasIndex(new[] { "NombrePermiso" }, "UK_Permisos_NombrePermiso")
                        .IsUnique();

                    b.ToTable("Permisos");
                });

            modelBuilder.Entity("LaundryManagement.Infrastructure.Role", b =>
                {
                    b.Property<int>("RolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RolID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RolId"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("RolId");

                    b.HasIndex(new[] { "Activo" }, "IX_Roles_Activo");

                    b.HasIndex(new[] { "NombreRol" }, "UK_Roles_NombreRol")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("LaundryManagement.Infrastructure.RolesPermiso", b =>
                {
                    b.Property<int>("RolPermisoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RolPermisoID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RolPermisoId"));

                    b.Property<int>("PermisoId")
                        .HasColumnType("int")
                        .HasColumnName("PermisoID");

                    b.Property<int>("RolId")
                        .HasColumnType("int")
                        .HasColumnName("RolID");

                    b.HasKey("RolPermisoId");

                    b.HasIndex(new[] { "PermisoId" }, "IX_RolesPermisos_PermisoID");

                    b.HasIndex(new[] { "RolId" }, "IX_RolesPermisos_RolID");

                    b.HasIndex(new[] { "RolId", "PermisoId" }, "UK_RolesPermisos_Rol_Permiso")
                        .IsUnique();

                    b.ToTable("RolesPermisos");
                });

            modelBuilder.Entity("LaundryManagement.Infrastructure.Servicio", b =>
                {
                    b.Property<int>("ServicioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ServicioID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServicioId"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int")
                        .HasColumnName("CategoriaID");

                    b.Property<string>("CodigoServicio")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("NombreServicio")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal?>("PesoMaximo")
                        .HasColumnType("decimal(6, 2)");

                    b.Property<decimal?>("PesoMinimo")
                        .HasColumnType("decimal(6, 2)");

                    b.Property<decimal?>("PrecioPorKilo")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("TiempoEstimado")
                        .HasColumnType("int");

                    b.Property<string>("TipoCobroServicio")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("ServicioId");

                    b.HasIndex(new[] { "Activo" }, "IX_Servicios_Activo");

                    b.HasIndex(new[] { "CategoriaId" }, "IX_Servicios_CategoriaID");

                    b.HasIndex(new[] { "TipoCobroServicio" }, "IX_Servicios_TipoCobroServicio");

                    b.HasIndex(new[] { "CodigoServicio" }, "UK_Servicios_CodigoServicio")
                        .IsUnique();

                    b.ToTable("Servicios");
                });

            modelBuilder.Entity("LaundryManagement.Infrastructure.ServiciosPrenda", b =>
                {
                    b.Property<int>("ServicioPrendaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ServicioPrendaID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServicioPrendaId"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("FechaActualizacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("ServicioId")
                        .HasColumnType("int")
                        .HasColumnName("ServicioID");

                    b.Property<int>("TipoPrendaId")
                        .HasColumnType("int")
                        .HasColumnName("TipoPrendaID");

                    b.HasKey("ServicioPrendaId");

                    b.HasIndex(new[] { "ServicioId" }, "IX_ServiciosPrendas_ServicioID");

                    b.HasIndex(new[] { "TipoPrendaId" }, "IX_ServiciosPrendas_TipoPrendaID");

                    b.HasIndex(new[] { "ServicioId", "TipoPrendaId" }, "UK_ServiciosPrendas_Servicio_Prenda")
                        .IsUnique();

                    b.ToTable("ServiciosPrendas", t =>
                        {
                            t.HasTrigger("TRG_ServiciosPrendas_ValidarTipoServicio");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("LaundryManagement.Infrastructure.TiposPrendum", b =>
                {
                    b.Property<int>("TipoPrendaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TipoPrendaID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoPrendaId"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("NombrePrenda")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("TipoPrendaId");

                    b.HasIndex(new[] { "NombrePrenda" }, "UK_TiposPrenda_NombrePrenda")
                        .IsUnique();

                    b.ToTable("TiposPrenda");
                });

            modelBuilder.Entity("LaundryManagement.Infrastructure.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UsuarioID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int?>("CreadoPor")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("UltimoAcceso")
                        .HasColumnType("datetime");

                    b.HasKey("UsuarioId");

                    b.HasIndex(new[] { "Activo" }, "IX_Usuarios_Activo");

                    b.HasIndex(new[] { "CreadoPor" }, "IX_Usuarios_CreadoPor")
                        .HasFilter("([CreadoPor] IS NOT NULL)");

                    b.HasIndex(new[] { "Email" }, "UK_Usuarios_Email")
                        .IsUnique();

                    b.HasIndex(new[] { "NombreUsuario" }, "UK_Usuarios_NombreUsuario")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("LaundryManagement.Infrastructure.UsuariosRole", b =>
                {
                    b.Property<int>("UsuarioRolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UsuarioRolID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioRolId"));

                    b.Property<DateTime>("FechaAsignacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("RolId")
                        .HasColumnType("int")
                        .HasColumnName("RolID");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("UsuarioID");

                    b.HasKey("UsuarioRolId");

                    b.HasIndex(new[] { "RolId" }, "IX_UsuariosRoles_RolID");

                    b.HasIndex(new[] { "UsuarioId" }, "IX_UsuariosRoles_UsuarioID");

                    b.HasIndex(new[] { "UsuarioId", "RolId" }, "UK_UsuariosRoles_Usuario_Rol")
                        .IsUnique();

                    b.ToTable("UsuariosRoles");
                });

            modelBuilder.Entity("LaundryManagement.Infrastructure.AuditoriaGeneral", b =>
                {
                    b.HasOne("LaundryManagement.Infrastructure.Usuario", "Usuario")
                        .WithMany("AuditoriaGenerals")
                        .HasForeignKey("UsuarioId")
                        .IsRequired()
                        .HasConstraintName("FK_AuditoriaGeneral_UsuarioID");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("LaundryManagement.Infrastructure.Cliente", b =>
                {
                    b.HasOne("LaundryManagement.Infrastructure.Usuario", "RegistradoPorNavigation")
                        .WithMany("Clientes")
                        .HasForeignKey("RegistradoPor")
                        .IsRequired()
                        .HasConstraintName("FK_Clientes_RegistradoPor");

                    b.Navigation("RegistradoPorNavigation");
                });

            modelBuilder.Entity("LaundryManagement.Infrastructure.CombosDetalle", b =>
                {
                    b.HasOne("LaundryManagement.Infrastructure.Combo", "Combo")
                        .WithMany("CombosDetalles")
                        .HasForeignKey("ComboId")
                        .IsRequired()
                        .HasConstraintName("FK_CombosDetalle_ComboID");

                    b.HasOne("LaundryManagement.Infrastructure.ServiciosPrenda", "ServicioPrenda")
                        .WithMany("CombosDetalles")
                        .HasForeignKey("ServicioPrendaId")
                        .IsRequired()
                        .HasConstraintName("FK_CombosDetalle_ServicioPrendaID");

                    b.Navigation("Combo");

                    b.Navigation("ServicioPrenda");
                });

            modelBuilder.Entity("LaundryManagement.Infrastructure.CortesCaja", b =>
                {
                    b.HasOne("LaundryManagement.Infrastructure.Usuario", "Cajero")
                        .WithMany("CortesCajas")
                        .HasForeignKey("CajeroId")
                        .IsRequired()
                        .HasConstraintName("FK_CortesCaja_Cajero");

                    b.Navigation("Cajero");
                });

            modelBuilder.Entity("LaundryManagement.Infrastructure.CortesCajaDetalle", b =>
                {
                    b.HasOne("LaundryManagement.Infrastructure.CortesCaja", "Corte")
                        .WithMany("CortesCajaDetalles")
                        .HasForeignKey("CorteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CortesCajaDetalle_Corte");

                    b.HasOne("LaundryManagement.Infrastructure.MetodosPago", "MetodoPago")
                        .WithMany("CortesCajaDetalles")
                        .HasForeignKey("MetodoPagoId")
                        .IsRequired()
                        .HasConstraintName("FK_CortesCajaDetalle_Metodo");

                    b.Navigation("Corte");

                    b.Navigation("MetodoPago");
                });

            modelBuilder.Entity("LaundryManagement.Infrastructure.HistorialEstadosOrden", b =>
                {
                    b.HasOne("LaundryManagement.Infrastructure.Usuario", "CambiadoPorNavigation")
                        .WithMany("HistorialEstadosOrdens")
                        .HasForeignKey("CambiadoPor")
                        .IsRequired()
                        .HasConstraintName("FK_HistorialEstadosOrden_CambiadoPor");

                    b.HasOne("LaundryManagement.Infrastructure.EstadosOrden", "EstadoOrden")
                        .WithMany("HistorialEstadosOrdens")
                        .HasForeignKey("EstadoOrdenId")
                        .IsRequired()
                        .HasConstraintName("FK_HistorialEstadosOrden_EstadoOrdenID");

                    b.HasOne("LaundryManagement.Infrastructure.Ordene", "Orden")
                        .WithMany("HistorialEstadosOrdens")
                        .HasForeignKey("OrdenId")
                        .IsRequired()
                        .HasConstraintName("FK_HistorialEstadosOrden_OrdenID");

                    b.Navigation("CambiadoPorNavigation");

                    b.Navigation("EstadoOrden");

                    b.Navigation("Orden");
                });

            modelBuilder.Entity("LaundryManagement.Infrastructure.HistorialReporte", b =>
                {
                    b.HasOne("LaundryManagement.Infrastructure.ConfiguracionReporte", "ConfigReporte")
                        .WithMany("HistorialReportes")
                        .HasForeignKey("ConfigReporteId")
                        .IsRequired()
                        .HasConstraintName("FK_HistorialReportes_ConfigReporteID");

                    b.Navigation("ConfigReporte");
                });

            modelBuilder.Entity("LaundryManagement.Infrastructure.Ordene", b =>
                {
                    b.HasOne("LaundryManagement.Infrastructure.Cliente", "Cliente")
                        .WithMany("Ordenes")
                        .HasForeignKey("ClienteId")
                        .IsRequired()
                        .HasConstraintName("FK_Ordenes_ClienteID");

                    b.HasOne("LaundryManagement.Infrastructure.Usuario", "EntregadoPorNavigation")
                        .WithMany("OrdeneEntregadoPorNavigations")
                        .HasForeignKey("EntregadoPor")
                        .HasConstraintName("FK_Ordenes_EntregadoPor");

                    b.HasOne("LaundryManagement.Infrastructure.EstadosOrden", "EstadoOrden")
                        .WithMany("Ordenes")
                        .HasForeignKey("EstadoOrdenId")
                        .IsRequired()
                        .HasConstraintName("FK_Ordenes_EstadoOrdenID");

                    b.HasOne("LaundryManagement.Infrastructure.Usuario", "RecibidoPorNavigation")
                        .WithMany("OrdeneRecibidoPorNavigations")
                        .HasForeignKey("RecibidoPor")
                        .IsRequired()
                        .HasConstraintName("FK_Ordenes_RecibidoPor");

                    b.Navigation("Cliente");

                    b.Navigation("EntregadoPorNavigation");

                    b.Navigation("EstadoOrden");

                    b.Navigation("RecibidoPorNavigation");
                });

            modelBuilder.Entity("LaundryManagement.Infrastructure.OrdenesDescuento", b =>
                {
                    b.HasOne("LaundryManagement.Infrastructure.Usuario", "AplicadoPorNavigation")
                        .WithMany("OrdenesDescuentos")
                        .HasForeignKey("AplicadoPor")
                        .IsRequired()
                        .HasConstraintName("FK_OrdenesDescuentos_AplicadoPor");

                    b.HasOne("LaundryManagement.Infrastructure.Combo", "Combo")
                        .WithMany("OrdenesDescuentos")
                        .HasForeignKey("ComboId")
                        .HasConstraintName("FK_OrdenesDescuentos_ComboID");

                    b.HasOne("LaundryManagement.Infrastructure.Descuento", "Descuento")
                        .WithMany("OrdenesDescuentos")
                        .HasForeignKey("DescuentoId")
                        .HasConstraintName("FK_OrdenesDescuentos_DescuentoID");

                    b.HasOne("LaundryManagement.Infrastructure.Ordene", "Orden")
                        .WithMany("OrdenesDescuentos")
                        .HasForeignKey("OrdenId")
                        .IsRequired()
                        .HasConstraintName("FK_OrdenesDescuentos_OrdenID");

                    b.Navigation("AplicadoPorNavigation");

                    b.Navigation("Combo");

                    b.Navigation("Descuento");

                    b.Navigation("Orden");
                });

            modelBuilder.Entity("LaundryManagement.Infrastructure.OrdenesDetalle", b =>
                {
                    b.HasOne("LaundryManagement.Infrastructure.Ordene", "Orden")
                        .WithMany("OrdenesDetalles")
                        .HasForeignKey("OrdenId")
                        .IsRequired()
                        .HasConstraintName("FK_OrdenesDetalle_OrdenID");

                    b.HasOne("LaundryManagement.Infrastructure.Servicio", "Servicio")
                        .WithMany("OrdenesDetalles")
                        .HasForeignKey("ServicioId")
                        .IsRequired()
                        .HasConstraintName("FK_OrdenesDetalle_ServicioID");

                    b.HasOne("LaundryManagement.Infrastructure.ServiciosPrenda", "ServicioPrenda")
                        .WithMany("OrdenesDetalles")
                        .HasForeignKey("ServicioPrendaId")
                        .HasConstraintName("FK_OrdenesDetalle_ServicioPrendaID");

                    b.Navigation("Orden");

                    b.Navigation("Servicio");

                    b.Navigation("ServicioPrenda");
                });

            modelBuilder.Entity("LaundryManagement.Infrastructure.Pago", b =>
                {
                    b.HasOne("LaundryManagement.Infrastructure.Ordene", "Orden")
                        .WithMany("Pagos")
                        .HasForeignKey("OrdenId")
                        .IsRequired()
                        .HasConstraintName("FK_Pagos_OrdenID");

                    b.HasOne("LaundryManagement.Infrastructure.Usuario", "RecibioPorNavigation")
                        .WithMany("Pagos")
                        .HasForeignKey("RecibioPor")
                        .IsRequired()
                        .HasConstraintName("FK_Pagos_RecibioPor");

                    b.Navigation("Orden");

                    b.Navigation("RecibioPorNavigation");
                });

            modelBuilder.Entity("LaundryManagement.Infrastructure.PagosDetalle", b =>
                {
                    b.HasOne("LaundryManagement.Infrastructure.MetodosPago", "MetodoPago")
                        .WithMany("PagosDetalles")
                        .HasForeignKey("MetodoPagoId")
                        .IsRequired()
                        .HasConstraintName("FK_PagosDetalle_MetodoPagoID");

                    b.HasOne("LaundryManagement.Infrastructure.Pago", "Pago")
                        .WithMany("PagosDetalles")
                        .HasForeignKey("PagoId")
                        .IsRequired()
                        .HasConstraintName("FK_PagosDetalle_PagoID");

                    b.Navigation("MetodoPago");

                    b.Navigation("Pago");
                });

            modelBuilder.Entity("LaundryManagement.Infrastructure.RolesPermiso", b =>
                {
                    b.HasOne("LaundryManagement.Infrastructure.Permiso", "Permiso")
                        .WithMany("RolesPermisos")
                        .HasForeignKey("PermisoId")
                        .IsRequired()
                        .HasConstraintName("FK_RolesPermisos_PermisoID");

                    b.HasOne("LaundryManagement.Infrastructure.Role", "Rol")
                        .WithMany("RolesPermisos")
                        .HasForeignKey("RolId")
                        .IsRequired()
                        .HasConstraintName("FK_RolesPermisos_RolID");

                    b.Navigation("Permiso");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("LaundryManagement.Infrastructure.Servicio", b =>
                {
                    b.HasOne("LaundryManagement.Infrastructure.Categoria", "Categoria")
                        .WithMany("Servicios")
                        .HasForeignKey("CategoriaId")
                        .IsRequired()
                        .HasConstraintName("FK_Servicios_CategoriaID");

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("LaundryManagement.Infrastructure.ServiciosPrenda", b =>
                {
                    b.HasOne("LaundryManagement.Infrastructure.Servicio", "Servicio")
                        .WithMany("ServiciosPrenda")
                        .HasForeignKey("ServicioId")
                        .IsRequired()
                        .HasConstraintName("FK_ServiciosPrendas_ServicioID");

                    b.HasOne("LaundryManagement.Infrastructure.TiposPrendum", "TipoPrenda")
                        .WithMany("ServiciosPrenda")
                        .HasForeignKey("TipoPrendaId")
                        .IsRequired()
                        .HasConstraintName("FK_ServiciosPrendas_TipoPrendaID");

                    b.Navigation("Servicio");

                    b.Navigation("TipoPrenda");
                });

            modelBuilder.Entity("LaundryManagement.Infrastructure.Usuario", b =>
                {
                    b.HasOne("LaundryManagement.Infrastructure.Usuario", "CreadoPorNavigation")
                        .WithMany("InverseCreadoPorNavigation")
                        .HasForeignKey("CreadoPor")
                        .HasConstraintName("FK_Usuarios_CreadoPor");

                    b.Navigation("CreadoPorNavigation");
                });

            modelBuilder.Entity("LaundryManagement.Infrastructure.UsuariosRole", b =>
                {
                    b.HasOne("LaundryManagement.Infrastructure.Role", "Rol")
                        .WithMany("UsuariosRoles")
                        .HasForeignKey("RolId")
                        .IsRequired()
                        .HasConstraintName("FK_UsuariosRoles_RolID");

                    b.HasOne("LaundryManagement.Infrastructure.Usuario", "Usuario")
                        .WithMany("UsuariosRoles")
                        .HasForeignKey("UsuarioId")
                        .IsRequired()
                        .HasConstraintName("FK_UsuariosRoles_UsuarioID");

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("LaundryManagement.Infrastructure.Categoria", b =>
                {
                    b.Navigation("Servicios");
                });

            modelBuilder.Entity("LaundryManagement.Infrastructure.Cliente", b =>
                {
                    b.Navigation("Ordenes");
                });

            modelBuilder.Entity("LaundryManagement.Infrastructure.Combo", b =>
                {
                    b.Navigation("CombosDetalles");

                    b.Navigation("OrdenesDescuentos");
                });

            modelBuilder.Entity("LaundryManagement.Infrastructure.ConfiguracionReporte", b =>
                {
                    b.Navigation("HistorialReportes");
                });

            modelBuilder.Entity("LaundryManagement.Infrastructure.CortesCaja", b =>
                {
                    b.Navigation("CortesCajaDetalles");
                });

            modelBuilder.Entity("LaundryManagement.Infrastructure.Descuento", b =>
                {
                    b.Navigation("OrdenesDescuentos");
                });

            modelBuilder.Entity("LaundryManagement.Infrastructure.EstadosOrden", b =>
                {
                    b.Navigation("HistorialEstadosOrdens");

                    b.Navigation("Ordenes");
                });

            modelBuilder.Entity("LaundryManagement.Infrastructure.MetodosPago", b =>
                {
                    b.Navigation("CortesCajaDetalles");

                    b.Navigation("PagosDetalles");
                });

            modelBuilder.Entity("LaundryManagement.Infrastructure.Ordene", b =>
                {
                    b.Navigation("HistorialEstadosOrdens");

                    b.Navigation("OrdenesDescuentos");

                    b.Navigation("OrdenesDetalles");

                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("LaundryManagement.Infrastructure.Pago", b =>
                {
                    b.Navigation("PagosDetalles");
                });

            modelBuilder.Entity("LaundryManagement.Infrastructure.Permiso", b =>
                {
                    b.Navigation("RolesPermisos");
                });

            modelBuilder.Entity("LaundryManagement.Infrastructure.Role", b =>
                {
                    b.Navigation("RolesPermisos");

                    b.Navigation("UsuariosRoles");
                });

            modelBuilder.Entity("LaundryManagement.Infrastructure.Servicio", b =>
                {
                    b.Navigation("OrdenesDetalles");

                    b.Navigation("ServiciosPrenda");
                });

            modelBuilder.Entity("LaundryManagement.Infrastructure.ServiciosPrenda", b =>
                {
                    b.Navigation("CombosDetalles");

                    b.Navigation("OrdenesDetalles");
                });

            modelBuilder.Entity("LaundryManagement.Infrastructure.TiposPrendum", b =>
                {
                    b.Navigation("ServiciosPrenda");
                });

            modelBuilder.Entity("LaundryManagement.Infrastructure.Usuario", b =>
                {
                    b.Navigation("AuditoriaGenerals");

                    b.Navigation("Clientes");

                    b.Navigation("CortesCajas");

                    b.Navigation("HistorialEstadosOrdens");

                    b.Navigation("InverseCreadoPorNavigation");

                    b.Navigation("OrdeneEntregadoPorNavigations");

                    b.Navigation("OrdeneRecibidoPorNavigations");

                    b.Navigation("OrdenesDescuentos");

                    b.Navigation("Pagos");

                    b.Navigation("UsuariosRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
